// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated with the command below against `runtime/`, the minimal benchmark runtime. The machine
// named below is not reference hardware: regenerate on reference hardware before production use.
// CI regenerates this file on every push (job `weights`) and uploads it as an artifact.

//! Autogenerated weights for `pallet_escrow`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 60.0.0
//! DATE: 2026-09-30, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `f45dda565906`, CPU: `11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /target/tools/frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// /target/release/wbuild/escrow-bench-runtime/escrow_bench_runtime.compact.wasm
// --pallet
// pallet_escrow
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// .maintain/frame-weight-template.hbs
// --header
// .maintain/weights-header.txt
// --output
// pallets/escrow/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_escrow`.
pub trait WeightInfo {
	fn create(m: u32, ) -> Weight;
	fn release() -> Weight;
	fn refund() -> Weight;
	fn cancel() -> Weight;
	fn submit() -> Weight;
	fn dispute() -> Weight;
	fn claim() -> Weight;
	fn resolve() -> Weight;
}

/// Weights for `pallet_escrow` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Escrow::NextEscrowId` (r:1 w:1)
	/// Proof: `Escrow::NextEscrowId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Escrow::Escrows` (r:0 w:1)
	/// Proof: `Escrow::Escrows` (`max_values`: None, `max_size`: Some(472), added: 2947, mode: `MaxEncodedLen`)
	/// The range of component `m` is `[1, 16]`.
	fn create(m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `6196`
		// Minimum execution time: 64_353_000 picoseconds.
		Weight::from_parts(131_819_216, 6196)
			// Standard Error: 28_695
			.saturating_add(Weight::from_parts(53_124, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `Escrow::Escrows` (r:1 w:1)
	/// Proof: `Escrow::Escrows` (`max_values`: None, `max_size`: Some(472), added: 2947, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:3)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn release() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `551`
		//  Estimated: `8799`
		// Minimum execution time: 100_854_000 picoseconds.
		Weight::from_parts(131_116_000, 8799)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `Escrow::Escrows` (r:1 w:1)
	/// Proof: `Escrow::Escrows` (`max_values`: None, `max_size`: Some(472), added: 2947, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn refund() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `449`
		//  Estimated: `6196`
		// Minimum execution time: 64_184_000 picoseconds.
		Weight::from_parts(95_483_000, 6196)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Escrow::Escrows` (r:1 w:1)
	/// Proof: `Escrow::Escrows` (`max_values`: None, `max_size`: Some(472), added: 2947, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn cancel() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `449`
		//  Estimated: `6196`
		// Minimum execution time: 64_686_000 picoseconds.
		Weight::from_parts(82_018_000, 6196)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Escrow::Escrows` (r:1 w:1)
	/// Proof: `Escrow::Escrows` (`max_values`: None, `max_size`: Some(472), added: 2947, mode: `MaxEncodedLen`)
	fn submit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `243`
		//  Estimated: `3937`
		// Minimum execution time: 14_362_000 picoseconds.
		Weight::from_parts(24_214_000, 3937)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Escrow::Escrows` (r:1 w:1)
	/// Proof: `Escrow::Escrows` (`max_values`: None, `max_size`: Some(472), added: 2947, mode: `MaxEncodedLen`)
	fn dispute() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `248`
		//  Estimated: `3937`
		// Minimum execution time: 14_153_000 picoseconds.
		Weight::from_parts(19_188_000, 3937)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Escrow::Escrows` (r:1 w:1)
	/// Proof: `Escrow::Escrows` (`max_values`: None, `max_size`: Some(472), added: 2947, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:3)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn claim() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `556`
		//  Estimated: `8799`
		// Minimum execution time: 101_179_000 picoseconds.
		Weight::from_parts(120_976_000, 8799)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `Escrow::Escrows` (r:1 w:1)
	/// Proof: `Escrow::Escrows` (`max_values`: None, `max_size`: Some(472), added: 2947, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:3)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn resolve() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `556`
		//  Estimated: `8799`
		// Minimum execution time: 131_071_000 picoseconds.
		Weight::from_parts(160_316_000, 8799)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Escrow::NextEscrowId` (r:1 w:1)
	/// Proof: `Escrow::NextEscrowId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Escrow::Escrows` (r:0 w:1)
	/// Proof: `Escrow::Escrows` (`max_values`: None, `max_size`: Some(472), added: 2947, mode: `MaxEncodedLen`)
	/// The range of component `m` is `[1, 16]`.
	fn create(m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `6196`
		// Minimum execution time: 64_353_000 picoseconds.
		Weight::from_parts(131_819_216, 6196)
			// Standard Error: 28_695
			.saturating_add(Weight::from_parts(53_124, 0).saturating_mul(m.into()))
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `Escrow::Escrows` (r:1 w:1)
	/// Proof: `Escrow::Escrows` (`max_values`: None, `max_size`: Some(472), added: 2947, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:3)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn release() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `551`
		//  Estimated: `8799`
		// Minimum execution time: 100_854_000 picoseconds.
		Weight::from_parts(131_116_000, 8799)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `Escrow::Escrows` (r:1 w:1)
	/// Proof: `Escrow::Escrows` (`max_values`: None, `max_size`: Some(472), added: 2947, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn refund() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `449`
		//  Estimated: `6196`
		// Minimum execution time: 64_184_000 picoseconds.
		Weight::from_parts(95_483_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Escrow::Escrows` (r:1 w:1)
	/// Proof: `Escrow::Escrows` (`max_values`: None, `max_size`: Some(472), added: 2947, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn cancel() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `449`
		//  Estimated: `6196`
		// Minimum execution time: 64_686_000 picoseconds.
		Weight::from_parts(82_018_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Escrow::Escrows` (r:1 w:1)
	/// Proof: `Escrow::Escrows` (`max_values`: None, `max_size`: Some(472), added: 2947, mode: `MaxEncodedLen`)
	fn submit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `243`
		//  Estimated: `3937`
		// Minimum execution time: 14_362_000 picoseconds.
		Weight::from_parts(24_214_000, 3937)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Escrow::Escrows` (r:1 w:1)
	/// Proof: `Escrow::Escrows` (`max_values`: None, `max_size`: Some(472), added: 2947, mode: `MaxEncodedLen`)
	fn dispute() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `248`
		//  Estimated: `3937`
		// Minimum execution time: 14_153_000 picoseconds.
		Weight::from_parts(19_188_000, 3937)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Escrow::Escrows` (r:1 w:1)
	/// Proof: `Escrow::Escrows` (`max_values`: None, `max_size`: Some(472), added: 2947, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:3)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn claim() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `556`
		//  Estimated: `8799`
		// Minimum execution time: 101_179_000 picoseconds.
		Weight::from_parts(120_976_000, 8799)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `Escrow::Escrows` (r:1 w:1)
	/// Proof: `Escrow::Escrows` (`max_values`: None, `max_size`: Some(472), added: 2947, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:3)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn resolve() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `556`
		//  Estimated: `8799`
		// Minimum execution time: 131_071_000 picoseconds.
		Weight::from_parts(160_316_000, 8799)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
}
